'use client';

import { useInView } from '@/hooks/useInView';

type Job = {
  company: string;
  role: string;
  dates: string;
  context: string;
  badge?: string;
  bullets: string[];
};

const JOBS: Job[] = [
  {
    company: 'Xebia IT Architects',
    role: 'Software Engineer — Platform & Full Stack',
    dates: 'Jul 2023 — Present',
    context: 'Remote · Client: Premium Parking, US',
    bullets: [
      'Operated AWS production infrastructure across 12 accounts, 4 environments, 25+ cloud services, and 10 applications serving millions of users at 10K+ req/s during US peak hours; maintained 99.9% availability with 24/7 on-call ownership.',
      'Reduced monthly AWS spend from ~$16k–$18k to ~$8k–$10k (40%+) through compute right-sizing, log retention tuning, S3 Glacier lifecycle policies, and capacity optimization.',
      'Improved release frequency from 2–4 to 6–12 deployments/month across 8 applications by redesigning GitHub Actions and AWS CDK CI/CD workflows; replaced manual ECS rollback with automated previous-image redeployment.',
      'Architected and delivered production SSO migration from SOAP-based auth to AWS Cognito with Azure AD/OIDC — built CognitoSessionValidator middleware, dual-write password sync, email-domain tenant routing, and zero-downtime rollout via Flipper feature flags.',
      'Built a mass email communication platform with role-based scheduling, S3/CarrierWave file attachments, custom template engine with permissions API, and market-scoped access controls — shipped full-stack from Rails backend to React frontend.',
      'Delivered TextPay citation SMS payment integration with GlideParcs enforcement API handling international phone normalization and citation formatting.',
      'Reduced daily alert volume from 100+ to 20–30 and MTTA from ~1 hour to ~15 minutes through CloudWatch observability improvements and runbook-driven triage.',
      'Hardened security through Rack::Attack OTP throttling, XSS remediation, AWS Secrets Manager integration, and AWS Inspector scanning supporting SOC 2 readiness.',
    ],
  },
  {
    company: 'Turing',
    role: 'AI/IaC Engineer',
    dates: 'Jul 2025 — Jan 2026',
    context: 'Remote',
    badge: 'Contract',
    bullets: [
      'Evaluated and corrected IaC code generated by large language models (Amazon Nova, Sora) — identified model defects, authored ideal reference solutions across Terraform, AWS CDK, CDKTF, Pulumi, and CloudFormation.',
      'Built a Python batch automation system to execute all engineer task submissions sequentially, collect outputs, and package for client distribution and local reproducibility.',
      'Developed hands-on expertise across the full IaC ecosystem — Terraform, CDK, CDKTF, Pulumi, and CloudFormation — validating correctness, security, and best practices across all major frameworks.',
    ],
  },
  {
    company: 'Xebia IT Architects',
    role: 'Software Engineer',
    dates: 'Jul 2022 — Jun 2023',
    context: 'Remote · Client: Premium Parking, US',
    bullets: [
      'Led Heroku-to-AWS migration of production Rails/PostgreSQL platform — improved uptime, response time, database performance, and eliminated infrastructure scaling limitations.',
      'Contributed to monolith modernization using microfrontend and microservice patterns with React, Hasura GraphQL, ECS, and PostgreSQL.',
      'Automated RDS backup/restore using AWS Backup with weekly, monthly, quarterly, and annual retention schedules and custom KMS encryption.',
      'Optimized PostgreSQL with read replicas, write/read query routing, table partitioning, and Sidekiq background job tuning.',
    ],
  },
  {
    company: 'Xebia IT Architects',
    role: 'Software Engineer Intern',
    dates: 'Sep 2021 — Jun 2022',
    context: 'Hyderabad, India',
    bullets: [
      'Built internal AWS CDK CLI tooling for consistent provisioning of S3, RDS, ECS, ECR, and IAM resources, reducing environment setup time and configuration drift.',
      'Developed Go/Lambda APIs and contributed to Docker containerization and GitHub Actions CI/CD automation.',
    ],
  },
];

function JobCard({ job, index }: { job: Job; index: number }) {
  const { ref, inView } = useInView();

  return (
    <div
      ref={ref as React.RefObject<HTMLDivElement>}
      className={`relative pl-8 reveal ${inView ? 'visible' : ''}`}
      style={{ transitionDelay: `${index * 80}ms` }}
    >
      {/* Timeline dot */}
      <div
        className="absolute left-0 top-[6px] w-2.5 h-2.5 rounded-full border-2 border-[#3b82f6] bg-[#0a0a0a] z-10"
        aria-hidden="true"
      />

      <div className="pb-12 last:pb-0">
        {/* Header */}
        <div className="flex flex-wrap items-start gap-x-3 gap-y-1 mb-1.5">
          <h3 className="text-[16px] font-semibold text-[#f0f0f0] leading-tight">{job.role}</h3>
          {job.badge && (
            <span className="inline-flex items-center px-2 py-0.5 rounded-md bg-[#1a2535] border border-[#1e3050] text-[#60a5fa] text-[11px] font-semibold uppercase tracking-wide">
              {job.badge}
            </span>
          )}
        </div>
        <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mb-5">
          <span className="text-[14px] font-medium text-[#555555]">{job.company}</span>
          <span className="text-[#2a2a2a]">·</span>
          <span className="text-[13px] text-[#444444]">{job.dates}</span>
          <span className="text-[#2a2a2a]">·</span>
          <span className="text-[13px] text-[#444444]">{job.context}</span>
        </div>

        {/* Bullets */}
        <ul className="space-y-2.5">
          {job.bullets.map((bullet, i) => (
            <li key={i} className="flex gap-3 text-[14px] leading-[1.7] text-[#777777]">
              <span className="text-[#2e2e2e] mt-[8px] shrink-0 text-[8px]">▪</span>
              <span>{bullet}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default function Experience() {
  return (
    <section id="experience" className="py-28 md:py-36 border-t border-[#111111]">
      <div className="max-w-6xl mx-auto px-5 sm:px-8">
        <p className="text-[#3b82f6] text-[11.5px] font-semibold uppercase tracking-[0.15em] mb-3">
          Work History
        </p>
        <h2 className="text-[36px] sm:text-[44px] font-bold text-[#f5f5f5] tracking-tight leading-[1.1] mb-16">
          Experience
        </h2>

        {/* Timeline container */}
        <div className="relative">
          {/* Vertical line */}
          <div
            className="timeline-line absolute left-[4px] top-0 bottom-0 w-px"
            aria-hidden="true"
          />
          <div className="space-y-0">
            {JOBS.map((job, i) => (
              <JobCard key={`${job.company}-${job.dates}`} job={job} index={i} />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
