'use client';

import { motion } from 'framer-motion';

type Job = {
  company: string;
  role: string;
  dates: string;
  context: string;
  badge?: { label: string; color: 'purple' };
  current?: boolean;
  bullets: string[];
};

const JOBS: Job[] = [
  {
    company: 'Xebia IT Architects',
    role: 'Software Engineer — Platform & Full Stack',
    dates: 'Jul 2023 — Present',
    context: 'Remote · Client: Premium Parking, US',
    current: true,
    bullets: [
      'Operated AWS production infrastructure across 12 accounts, 4 environments, 25+ cloud services, and 10 applications serving millions of users at 10K+ req/s during US peak hours; maintained 99.9% availability with 24/7 on-call ownership.',
      'Reduced monthly AWS spend from ~$16k–$18k to ~$8k–$10k (40%+) through compute right-sizing, log retention tuning, S3 Glacier lifecycle policies, and capacity optimization.',
      'Improved release frequency from 2–4 to 6–12 deployments/month across 8 applications by redesigning GitHub Actions and AWS CDK CI/CD workflows; replaced manual ECS rollback with automated previous-image redeployment.',
      'Architected and delivered production SSO migration from SOAP-based auth to AWS Cognito with Azure AD/OIDC — built CognitoSessionValidator middleware, dual-write password sync, email-domain tenant routing, and zero-downtime rollout via Flipper feature flags.',
      'Built a mass email communication platform with role-based scheduling, S3/CarrierWave file attachments, custom template engine with permissions API, and market-scoped access controls — shipped full-stack from Rails backend to React frontend.',
      'Delivered TextPay citation SMS payment integration with GlideParcs enforcement API handling international phone normalization and citation formatting.',
      'Reduced daily alert volume from 100+ to 20–30 and MTTA from ~1 hour to ~15 minutes through CloudWatch observability improvements and runbook-driven triage.',
      'Hardened security through Rack::Attack OTP throttling, XSS remediation, AWS Secrets Manager integration, and AWS Inspector scanning supporting SOC 2 readiness.',
    ],
  },
  {
    company: 'Turing',
    role: 'AI/IaC Engineer',
    dates: 'Jul 2025 — Jan 2026',
    context: 'Remote',
    badge: { label: 'Contract', color: 'purple' },
    bullets: [
      'Evaluated and corrected IaC code generated by large language models (Amazon Nova, Sora) — identified model defects, authored ideal reference solutions across Terraform, AWS CDK, CDKTF, Pulumi, and CloudFormation.',
      'Built a Python batch automation system to execute all engineer task submissions sequentially, collect outputs, and package for client distribution and local reproducibility.',
      'Developed hands-on expertise across the full IaC ecosystem — Terraform, CDK, CDKTF, Pulumi, and CloudFormation — validating correctness, security, and best practices across all major frameworks.',
    ],
  },
  {
    company: 'Xebia IT Architects',
    role: 'Software Engineer',
    dates: 'Jul 2022 — Jun 2023',
    context: 'Remote · Client: Premium Parking, US',
    bullets: [
      'Led Heroku-to-AWS migration of production Rails/PostgreSQL platform — improved uptime, response time, database performance, and eliminated infrastructure scaling limitations.',
      'Contributed to monolith modernization using microfrontend and microservice patterns with React, Hasura GraphQL, ECS, and PostgreSQL.',
      'Automated RDS backup/restore using AWS Backup with weekly, monthly, quarterly, and annual retention schedules and custom KMS encryption.',
      'Optimized PostgreSQL with read replicas, write/read query routing, table partitioning, and Sidekiq background job tuning.',
    ],
  },
  {
    company: 'Xebia IT Architects',
    role: 'Software Engineer Intern',
    dates: 'Sep 2021 — Jun 2022',
    context: 'Hyderabad, India',
    bullets: [
      'Built internal AWS CDK CLI tooling for consistent provisioning of S3, RDS, ECS, ECR, and IAM resources, reducing environment setup time and configuration drift.',
      'Developed Go/Lambda APIs and contributed to Docker containerization and GitHub Actions CI/CD automation.',
    ],
  },
];

export default function Experience() {
  return (
    <section id="experience" className="py-28 md:py-36 border-t border-[#111]">
      <div className="max-w-6xl mx-auto px-5 sm:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <p className="text-[#3b82f6] text-[11px] font-semibold uppercase tracking-[0.18em] mb-3">Work History</p>
          <h2 className="text-[36px] sm:text-[44px] font-bold text-[#f0f0f0] tracking-tight leading-[1.08] mb-16">
            Experience
          </h2>
        </motion.div>

        {/* Timeline */}
        <div className="relative">
          {/* Vertical line */}
          <div className="absolute left-[19px] top-0 bottom-0 w-px timeline-line" aria-hidden="true" />

          <div className="space-y-4">
            {JOBS.map((job, i) => {
              const isPurple = job.badge?.color === 'purple';
              return (
                <motion.div
                  key={`${job.company}-${job.dates}`}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1, duration: 0.5, ease: 'easeOut' as const }}
                  className="relative pl-12"
                >
                  {/* Timeline dot */}
                  {job.current ? (
                    <span className="absolute left-[11px] top-[22px] flex items-center justify-center" aria-hidden="true">
                      <motion.span
                        animate={{ scale: [1, 1.6, 1], opacity: [0.6, 0, 0.6] }}
                        transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                        className="absolute inline-flex rounded-full w-5 h-5 bg-[#3b82f6]/30"
                      />
                      <span className="relative w-2.5 h-2.5 rounded-full bg-[#3b82f6]" />
                    </span>
                  ) : (
                    <span
                      className={`absolute left-[11px] top-[22px] w-2.5 h-2.5 rounded-full ring-4 ${
                        isPurple
                          ? 'bg-purple-500 ring-purple-500/20'
                          : 'bg-[#2a2a2a] ring-[#1a1a1a]'
                      }`}
                      aria-hidden="true"
                    />
                  )}

                  {/* Card */}
                  <div className="rounded-2xl border border-[#1a1a1a] bg-[#0e0e0e] p-6 hover:border-[#222] transition-colors duration-200">
                    {/* Header */}
                    <div className="flex flex-wrap items-start justify-between gap-2 mb-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="text-[15px] font-semibold text-[#e0e0e0]">{job.company}</span>
                        {job.badge && (
                          <span className="px-2 py-0.5 rounded-full border border-purple-500/20 bg-purple-500/10 text-purple-400 text-[10.5px] font-semibold uppercase tracking-wide">
                            {job.badge.label}
                          </span>
                        )}
                        {job.current && (
                          <span className="px-2 py-0.5 rounded-full border border-green-500/20 bg-green-500/10 text-green-400 text-[10.5px] font-semibold uppercase tracking-wide">
                            Current
                          </span>
                        )}
                      </div>
                      <span className="text-[13px] text-[#444] tabular shrink-0">{job.dates}</span>
                    </div>

                    <p className="text-[13px] text-[#3b82f6] mb-1">{job.role}</p>
                    <p className="text-[12px] text-[#333] mb-5">{job.context}</p>

                    {/* Bullets */}
                    <ul className="space-y-2">
                      {job.bullets.map((bullet, j) => (
                        <li key={j} className="flex gap-3 text-[13.5px] leading-[1.7] text-[#666]">
                          <span className="text-[#3b82f6] mt-[6px] shrink-0 text-[10px]">›</span>
                          <span>{bullet}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </motion.div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
}
